// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_music.Models;

#nullable disable

namespace project_music.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20260421055148_AddVipAndSystemPlaylistColumns")]
    partial class AddVipAndSystemPlaylistColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.Property<string>("SongId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("song_id");

                    b.HasKey("GenreId", "SongId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "SongId" }, "song_id");

                    b.ToTable("genre_song", (string)null);
                });

            modelBuilder.Entity("project_music.Models.Album", b =>
                {
                    b.Property<string>("AlbumId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("album_id");

                    b.Property<string>("AlbumType")
                        .IsRequired()
                        .HasColumnType("enum('SINGLE','EP','ALBUM')")
                        .HasColumnName("album_type");

                    b.Property<string>("ArtistId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("artist_id");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cover_url");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("AlbumId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ArtistId" }, "artist_id");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("project_music.Models.Artist", b =>
                {
                    b.Property<string>("ArtistId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("artist_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cover_url");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ArtistId")
                        .HasName("PRIMARY");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("project_music.Models.ArtistSong", b =>
                {
                    b.Property<string>("ArtistId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("artist_id");

                    b.Property<string>("SongId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("song_id");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('MAIN','FEATURED','PRODUCER')")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'MAIN'");

                    b.HasKey("ArtistId", "SongId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "SongId" }, "song_id")
                        .HasDatabaseName("song_id1");

                    b.ToTable("artist_song", (string)null);
                });

            modelBuilder.Entity("project_music.Models.AudioFile", b =>
                {
                    b.Property<string>("FileId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("file_id");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_url");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("enum('128KBPS','320KBPS','LOSSLESS')")
                        .HasColumnName("quality");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("SongId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("song_id");

                    b.HasKey("FileId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SongId" }, "song_id")
                        .HasDatabaseName("song_id2");

                    b.ToTable("audio_files", (string)null);
                });

            modelBuilder.Entity("project_music.Models.Episode", b =>
                {
                    b.Property<string>("EpisodeId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("episode_id");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("audio_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("PodcastId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("podcast_id");

                    b.Property<DateTime?>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("published_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("EpisodeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PodcastId" }, "podcast_id");

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("project_music.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("GenreId")
                        .HasName("PRIMARY");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("project_music.Models.PlayHistory", b =>
                {
                    b.Property<string>("HistoryId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("history_id");

                    b.Property<int>("ListenDurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("listen_duration_seconds");

                    b.Property<DateTime?>("PlayedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("played_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SongId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("song_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("HistoryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SongId" }, "song_id")
                        .HasDatabaseName("song_id3");

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("play_history", (string)null);
                });

            modelBuilder.Entity("project_music.Models.Playlist", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("playlist_id");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cover_url");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("'0'");

                    b.Property<bool?>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_public")
                        .HasDefaultValueSql("'1'");

                    b.Property<ulong>("IsSystemPlaylist")
                        .HasColumnType("bit")
                        .HasColumnName("IsSystemPlaylist");

                    b.Property<ulong>("IsVipOnly")
                        .HasColumnType("bit")
                        .HasColumnName("IsVipOnly");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("PlaylistId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id1");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("project_music.Models.PlaylistCollaborator", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("playlist_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('OWNER','EDITOR')")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'EDITOR'");

                    b.HasKey("PlaylistId", "UserId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id2");

                    b.ToTable("playlist_collaborators", (string)null);
                });

            modelBuilder.Entity("project_music.Models.PlaylistSong", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("playlist_id");

                    b.Property<string>("SongId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("song_id");

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PositionOrder")
                        .HasColumnType("int")
                        .HasColumnName("position_order");

                    b.HasKey("PlaylistId", "SongId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "SongId" }, "song_id")
                        .HasDatabaseName("song_id4");

                    b.ToTable("playlist_songs", (string)null);
                });

            modelBuilder.Entity("project_music.Models.Podcast", b =>
                {
                    b.Property<string>("PodcastId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("podcast_id");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cover_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("host_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("PodcastId")
                        .HasName("PRIMARY");

                    b.ToTable("podcasts", (string)null);
                });

            modelBuilder.Entity("project_music.Models.Song", b =>
                {
                    b.Property<string>("SongId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("song_id");

                    b.Property<string>("AlbumId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("album_id");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("cover_url");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<long?>("TotalPlays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("total_plays")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("SongId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AlbumId" }, "album_id");

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("project_music.Models.SongLyric", b =>
                {
                    b.Property<string>("LyricId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("lyric_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Language")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("language")
                        .HasDefaultValueSql("'vi'");

                    b.Property<string>("SongId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("song_id");

                    b.Property<string>("SyncType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('UNSYNCED','LINE_SYNCED','WORD_SYNCED')")
                        .HasColumnName("sync_type")
                        .HasDefaultValueSql("'UNSYNCED'");

                    b.HasKey("LyricId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SongId" }, "song_id")
                        .HasDatabaseName("song_id5");

                    b.ToTable("song_lyrics", (string)null);
                });

            modelBuilder.Entity("project_music.Models.SubscriptionPlan", b =>
                {
                    b.Property<string>("PlanId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("plan_id");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int")
                        .HasColumnName("duration_days");

                    b.Property<string>("Features")
                        .HasColumnType("json")
                        .HasColumnName("features");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.HasKey("PlanId")
                        .HasName("PRIMARY");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("project_music.Models.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("transaction_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("PaidAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("paid_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasColumnType("enum('MOMO','ZALOPAY','STRIPE','PAYPAL')")
                        .HasColumnName("payment_gateway");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('PENDING','SUCCESS','FAILED')")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PlanId" }, "plan_id");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id3");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("project_music.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("'0'");

                    b.Property<bool?>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_premium")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("PremiumExpiryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("premium_expiry_date");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("Role")
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("ZaloId")
                        .HasColumnType("longtext")
                        .HasColumnName("zalo_id");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("project_music.Models.UserDownload", b =>
                {
                    b.Property<string>("DownloadId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("download_id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("DownloadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("downloaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("SongId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("song_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("DownloadId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SongId" }, "song_id")
                        .HasDatabaseName("song_id6");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id4");

                    b.ToTable("user_downloads", (string)null);
                });

            modelBuilder.Entity("project_music.Models.UserFavoriteSong", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("SongId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("song_id");

                    b.Property<DateTime?>("LikedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("liked_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "SongId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "SongId" }, "song_id")
                        .HasDatabaseName("song_id7");

                    b.ToTable("user_favorite_songs", (string)null);
                });

            modelBuilder.Entity("project_music.Models.UserFollowArtist", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("ArtistId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("artist_id");

                    b.Property<DateTime?>("FollowedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("followed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "ArtistId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "ArtistId" }, "artist_id")
                        .HasDatabaseName("artist_id1");

                    b.ToTable("user_follow_artist", (string)null);
                });

            modelBuilder.Entity("project_music.Models.UserFollowUser", b =>
                {
                    b.Property<string>("FollowerId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("follower_id");

                    b.Property<string>("FollowingId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("following_id");

                    b.Property<DateTime?>("FollowedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("followed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FollowerId", "FollowingId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "FollowingId" }, "following_id");

                    b.ToTable("user_follow_user", (string)null);
                });

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.HasOne("project_music.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("genre_song_ibfk_1");

                    b.HasOne("project_music.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("genre_song_ibfk_2");
                });

            modelBuilder.Entity("project_music.Models.Album", b =>
                {
                    b.HasOne("project_music.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("albums_ibfk_1");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("project_music.Models.ArtistSong", b =>
                {
                    b.HasOne("project_music.Models.Artist", "Artist")
                        .WithMany("ArtistSongs")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("artist_song_ibfk_1");

                    b.HasOne("project_music.Models.Song", "Song")
                        .WithMany("ArtistSongs")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("artist_song_ibfk_2");

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("project_music.Models.AudioFile", b =>
                {
                    b.HasOne("project_music.Models.Song", "Song")
                        .WithMany("AudioFiles")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("audio_files_ibfk_1");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("project_music.Models.Episode", b =>
                {
                    b.HasOne("project_music.Models.Podcast", "Podcast")
                        .WithMany("Episodes")
                        .HasForeignKey("PodcastId")
                        .IsRequired()
                        .HasConstraintName("episodes_ibfk_1");

                    b.Navigation("Podcast");
                });

            modelBuilder.Entity("project_music.Models.PlayHistory", b =>
                {
                    b.HasOne("project_music.Models.Song", "Song")
                        .WithMany("PlayHistories")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("play_history_ibfk_2");

                    b.HasOne("project_music.Models.User", "User")
                        .WithMany("PlayHistories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("play_history_ibfk_1");

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_music.Models.Playlist", b =>
                {
                    b.HasOne("project_music.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("playlists_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_music.Models.PlaylistCollaborator", b =>
                {
                    b.HasOne("project_music.Models.Playlist", "Playlist")
                        .WithMany("PlaylistCollaborators")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("playlist_collaborators_ibfk_1");

                    b.HasOne("project_music.Models.User", "User")
                        .WithMany("PlaylistCollaborators")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("playlist_collaborators_ibfk_2");

                    b.Navigation("Playlist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_music.Models.PlaylistSong", b =>
                {
                    b.HasOne("project_music.Models.Playlist", "Playlist")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("playlist_songs_ibfk_1");

                    b.HasOne("project_music.Models.Song", "Song")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("playlist_songs_ibfk_2");

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("project_music.Models.Song", b =>
                {
                    b.HasOne("project_music.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("songs_ibfk_1");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("project_music.Models.SongLyric", b =>
                {
                    b.HasOne("project_music.Models.Song", "Song")
                        .WithMany("SongLyrics")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("song_lyrics_ibfk_1");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("project_music.Models.Transaction", b =>
                {
                    b.HasOne("project_music.Models.SubscriptionPlan", "Plan")
                        .WithMany("Transactions")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("transactions_ibfk_2");

                    b.HasOne("project_music.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("transactions_ibfk_1");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_music.Models.UserDownload", b =>
                {
                    b.HasOne("project_music.Models.Song", "Song")
                        .WithMany("UserDownloads")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("user_downloads_ibfk_2");

                    b.HasOne("project_music.Models.User", "User")
                        .WithMany("UserDownloads")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_downloads_ibfk_1");

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_music.Models.UserFavoriteSong", b =>
                {
                    b.HasOne("project_music.Models.Song", "Song")
                        .WithMany("UserFavoriteSongs")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("user_favorite_songs_ibfk_2");

                    b.HasOne("project_music.Models.User", "User")
                        .WithMany("UserFavoriteSongs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_favorite_songs_ibfk_1");

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_music.Models.UserFollowArtist", b =>
                {
                    b.HasOne("project_music.Models.Artist", "Artist")
                        .WithMany("UserFollowArtists")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("user_follow_artist_ibfk_2");

                    b.HasOne("project_music.Models.User", "User")
                        .WithMany("UserFollowArtists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_follow_artist_ibfk_1");

                    b.Navigation("Artist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_music.Models.UserFollowUser", b =>
                {
                    b.HasOne("project_music.Models.User", "Follower")
                        .WithMany("UserFollowUserFollowers")
                        .HasForeignKey("FollowerId")
                        .IsRequired()
                        .HasConstraintName("user_follow_user_ibfk_1");

                    b.HasOne("project_music.Models.User", "Following")
                        .WithMany("UserFollowUserFollowings")
                        .HasForeignKey("FollowingId")
                        .IsRequired()
                        .HasConstraintName("user_follow_user_ibfk_2");

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("project_music.Models.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("project_music.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("ArtistSongs");

                    b.Navigation("UserFollowArtists");
                });

            modelBuilder.Entity("project_music.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistCollaborators");

                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("project_music.Models.Podcast", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("project_music.Models.Song", b =>
                {
                    b.Navigation("ArtistSongs");

                    b.Navigation("AudioFiles");

                    b.Navigation("PlayHistories");

                    b.Navigation("PlaylistSongs");

                    b.Navigation("SongLyrics");

                    b.Navigation("UserDownloads");

                    b.Navigation("UserFavoriteSongs");
                });

            modelBuilder.Entity("project_music.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("project_music.Models.User", b =>
                {
                    b.Navigation("PlayHistories");

                    b.Navigation("PlaylistCollaborators");

                    b.Navigation("Playlists");

                    b.Navigation("Transactions");

                    b.Navigation("UserDownloads");

                    b.Navigation("UserFavoriteSongs");

                    b.Navigation("UserFollowArtists");

                    b.Navigation("UserFollowUserFollowers");

                    b.Navigation("UserFollowUserFollowings");
                });
#pragma warning restore 612, 618
        }
    }
}
